[workspace]
resolver = "2"

members = [
    "cli",
    "clients",
    "core", "gui",
    "keys", "logging",
    "macros",
    "proof_of_space",
    "puzzles",
    "serialize",
    "servers",
    "simulator",
    "tests"
]
