[workspace]
resolver = "3"
members = [
    "cli",
    "clients",
    "core",
    "gui/src-tauri",
    "keys",
    "logging",
    "macros",
    "parser_macro",
    "proof_of_space",
    "puzzles",
    "serialize",
    "servers",
    "simulator",
    "tests",
    "vdf",
    "weight-proof"
]

[workspace.package]
version = "3.0.0"
edition = "2024"
authors = ["James Hoerr jhoerr@galactechs.com"]
license = "Apache-2.0"
homepage = "https://github.com/GalactechsLLC/dg_xch_utils"
repository = "https://github.com/GalactechsLLC/dg_xch_utils"

[profile.bench]
debug = true
strip = "debuginfo"
