[package]
name = "dg_xch_clients"
version = "1.0.2"
edition = "2021"
authors = ["James Hoerr"]
description = "RPC and Websocket Clients the Chia Blockchain"

[dependencies]
async-trait = "0.1.58"
dg_xch_core = {version = "1.0.3", features = ["paperclip"] }
dg_xch_macros = "1.0.2"
dg_xch_pos = "1.0.2"
dg_xch_serialize = "1.0.2"
futures-util = "0.3.25"
hyper = {version="0.14.23", features=["full"]}
log = "0.4.17"
reqwest = {version="0.11.11", features=["json", "rustls-tls-webpki-roots"]}
rustls = {version = "0.20.7", features = ["dangerous_configuration"] }
rustls-pemfile = "1.0.1"
serde = { version = "1.0.149", features = ["derive"] }
serde_json = "1.0.89"
time = "0.3.21"
tokio = {version = "1.21.2", features=["rt-multi-thread", "sync", "signal", "macros", "process", "time", "fs", "net"]}
tokio-tungstenite = {version = "0.18.0", features = ["rustls-tls-webpki-roots", "rustls"] }
uuid = {version="1.2.2", features=["v4"]}