[package]
name = "dg_xch_clients"
version = "1.0.9"
edition = "2021"
authors = ["James Hoerr"]
description = "RPC and Websocket Clients the Chia Blockchain"
license = "Apache-2.0"
homepage = "https://github.com/GalactechsLLC/dg_xch_utils"
repository = "https://github.com/GalactechsLLC/dg_xch_utils/clients"

[dependencies]
async-trait = "0.1.73"
dashmap = "5.5.3"
dg_xch_core = {path = "../core", version = "1.0.9", features = ["paperclip"] }
dg_xch_macros = {path = "../macros", version="1.0.9"}
dg_xch_pos = {path = "../proof_of_space", version="1.0.9"}
dg_xch_serialize = {path = "../serialize", version="1.0.9"}
futures-util = "0.3.28"
hyper = {version="0.14.27", features=["full"]}
log = "0.4.20"
openssl = {version = "0.10.57", features = ["vendored"]}
reqwest = {version="0.11.22", features=["json", "rustls-tls-webpki-roots"]}
rustls = {version = "0.21.7", features = ["dangerous_configuration"] }
rustls-pemfile = "1.0.3"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
time = "0.3.30"
tokio = {version = "1.33.0", features=["rt-multi-thread", "sync", "signal", "macros", "process", "time", "fs", "net"]}
tokio-tungstenite = {version = "0.20.1", features = ["rustls-tls-webpki-roots", "rustls"] }
urlencoding = "2.1.3"
uuid = {version="1.4.1", features=["v4"]}