[package]
name = "dg_xch_gui"
description = "Native Galactechs node, wallets, plotting and farming desktop"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bip39 = { version = "2.2.2", features = ["rand"] }
blst = "0.3.16"
dg_xch_clients = { path = "../clients" }
dg_xch_core = { path = "../core", default-features = false, features = ["bls"] }
dg_xch_farmer = { path = "../farmer" }
dg_xch_keys = { path = "../keys" }
dg_xch_plotter = { path = "../plotter", features = ["vulkan"] }
dg_xch_pos2 = { path = "../proof_of_space/pos2", features = ["vulkan"] }
dg_xch_wallet = { path = "../wallet" }
directories = "6.0.0"
eframe = { version = "0.36.2", default-features = false, features = ["default_fonts", "wgpu", "wayland", "x11"] }
hex = "0.4.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tempfile = "3"
tokio = { version = "1.50.0", features = ["rt-multi-thread", "sync", "time", "macros"] }
zeroize = "1.9.0"
