[package]
name = "dg_xch_cli"
description = "CLI Utilities for the Chia Blockchain"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
name = "dg_xch_cli_lib"
path = "src/lib.rs"

[[bin]]
name = "dg"
path = "src/main.rs"

[dependencies]
async-trait = "0.1.89"
bip39 = {version= "2.2.2", features=["rand"] }
blst = { version = "0.3.16", features = ["portable"] }
clap = { version = "4.5.60", features = ["derive"] }
dashmap = "6.1.0"
dialoguer = "0.12.0"
dg_logger = { path="../logging", version="3.0.0" }
dg_xch_clients = {path = "../clients", version="3.0.0"}
dg_xch_core = {path = "../core", version = "3.0.0", default-features = false, features = ["bls"]}
dg_xch_keys = {path = "../keys", version="3.0.0"}
dg_xch_p2p = { path = "../p2p", version = "3.0.0" }
dg_xch_puzzles = {path = "../puzzles", version="3.0.0"}
dg_xch_serialize= {path = "../serialize", version="3.0.0"}
dg_full_node = { path = "../full-node", version = "3.0.0", default-features = false }
hex = "0.4.3"
lazy_static = "1.5.0"
log = "0.4.29"
num-traits = "0.2.19"
rand = "0.10.0"
serde_json = "1.0.149"
tokio = {version = "1.50.0", features=["rt-multi-thread", "sync", "signal", "macros", "process", "time", "fs", "net"]}

[target.'cfg(target_os = "linux")'.dependencies]
tikv-jemallocator = { version = "0.6", features = ["background_threads"] }

[target.'cfg(not(target_os = "linux"))'.dependencies]
tikv-jemallocator = "0.6"

[features]
default = ["sqlite"]
sqlite = ["dg_full_node/sqlite"]
coin-index = ["dg_full_node/coin-index"]
hint = ["coin-index", "dg_full_node/hint"]
postgres = ["dg_full_node/postgres"]
mmap = ["dg_full_node/mmap"]
profiling = ["dg_full_node/profiling", "tikv-jemallocator/profiling"]
