[package]
name = "dg_xch_pos"
description = "Compatibility facade and consensus dispatch for proof of space v1 and v2"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
dg_xch_core = { workspace = true }
dg_xch_pos1 = { path = "pos1", version = "3.0.0" }
dg_xch_pos2 = { path = "pos2", version = "3.0.0" }
dg_xch_pos_common = { path = "pos_common", version = "3.0.0" }
log = "0.4.29"
