[package]
name = "dg_xch_pos"
version = "1.0.2"
edition = "2021"
authors = ["James Hoerr"]
description = "Proof of Space library for the Chia Blockchain"

[dependencies]
blake3 = "1.3.1"
dg_xch_core = {path = "../core", features = ["paperclip"] }
dg_xch_serialize = {path = "../serialize"}
lazy_static = "1.4.0"
log = "0.4.17"
nix = "0.26.2"
num-traits = "=0.2.14"
rayon = "1.7.0"
sha2 = "0.10.6"
simple_logger = "4.0.0"