[package]
name = "dg_xch_pos"
version = "1.0.4"
edition = "2021"
authors = ["James Hoerr"]
description = "Proof of Space library for the Chia Blockchain"
license = "Apache-2.0"
homepage = "https://github.com/GalactechsLLC/dg_xch_utils"
repository = "https://github.com/GalactechsLLC/dg_xch_utils/proof_of_space"

[dependencies]
blake3 = "1.3.1"
dg_xch_core = {path = "../core", version = "1.0.4", features = ["paperclip"] }
dg_xch_serialize = {path = "../serialize", version="1.0.4"}
hex = "0.4.3"
lazy_static = "1.4.0"
log = "0.4.17"
nix = "0.26.2"
num-traits = "=0.2.14"
rayon = "1.7.0"
sha2 = "0.10.6"
simple_logger = "4.0.0"
