[package]
name = "dg_xch_core"
version = "1.2.1"
edition = "2021"
authors = ["James Hoerr"]
description = "Core library containing type/error definitions, CLVM tools, Consensus and Pool definitions"
license = "Apache-2.0"
homepage = "https://github.com/GalactechsLLC/dg_xch_utils"
repository = "https://github.com/GalactechsLLC/dg_xch_utils/core"

[dependencies]
bech32 = "0.9.1"
bip39 = {version= "2.0.0", features=["rand"] }
bls12_381 = "0.8.0"
blst = "0.3.11"
bytes = "1.5.0"
der = "0.7.8"
dg_xch_macros = {path = "../macros", version="1.2.1"}
dg_xch_serialize = {path = "../serialize", version="1.2.1"}
hex = "0.4.3"
hkdf = "0.12.3"
log = "0.4.20"
num-bigint = "0.4.4"
num-integer = "0.1.45"
num-traits = "0.2.17"
once_cell = "1.18.0"
paperclip = { version = "0.8.2", features = ["actix4"], optional = true }
rand = "0.8.5"
regex = "1.10.2"
rsa = { version = "0.9.4", features = ["std", "pem", "sha2"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
sha2 = { version = "0.10.8", features = ["oid"] }
simple_logger = "4.3.0"
tokio = {version = "1.34.0", features=["rt-multi-thread", "sync", "signal", "macros", "process", "time", "fs", "net"]}
x509-cert = { version = "0.2.4", features = ["std", "pem", "builder"] }
