[package]
name = "dg_xch_core"
version = "1.0.9"
edition = "2021"
authors = ["James Hoerr"]
description = "Core library containing type/error definitions, CLVM tools, Consensus and Pool definitions"
license = "Apache-2.0"
homepage = "https://github.com/GalactechsLLC/dg_xch_utils"
repository = "https://github.com/GalactechsLLC/dg_xch_utils/core"

[dependencies]
bech32 = "0.9.1"
bip39 = {version= "2.0.0", features=["rand"] }
bls12_381 = "0.8.0"
blst = "0.3.10"
bytes = "1.5.0"
dg_xch_macros = {path = "../macros", version="1.0.9"}
dg_xch_serialize = {path = "../serialize", version="1.0.9"}
hex = "0.4.3"
hkdf = "0.12.3"
lazy_static = "1.4.0"
log = "0.4.20"
num-bigint = "0.4.4"
num-integer = "0.1.45"
num-traits = "0.2.17"
openssl = "0.10.57"
paperclip = { version = "0.8.2", features = ["actix4"], optional = true }
regex = "1.10.1"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
sha2 = "0.10.8"
simple_logger = "4.2.0"
tokio = {version = "1.33.0", features=["rt-multi-thread", "sync", "signal", "macros", "process", "time", "fs", "net"]}

[features]
paperclip = ["dep:paperclip"]
