[package]
name = "dg_xch_gui"
description = "GUI for the dg_xch_utils"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
name = "dg_xch_gui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
shared-types = { path = "../shared_crates/shared-types", version = "0.1.0" }
tauri-build = { version = "2.5.5", features = [] }

[dependencies]
chacha20poly1305 = {version = "0.10.1", default-features = false, features = ["alloc"] }
dg_xch_keys = { path="../../keys", version="3.0.0"}
keyring = "3.6.3"
#petname = "3.0.0-alpha.2"
lifehash = "0.1.0"
rand_chacha = "0.10.0"
serde_json = "1.0.149"
serde = { version = "1.0.228", features = ["derive"] }
sha2 = "0.10.9"
log = "0.4.29"
shared-types = { path = "../shared_crates/shared-types", version = "0.1.0" }
tauri = { version = "2.10.2", features = [] }
tauri-plugin-log = "2.8.0"
