[package]
name = "dg_xch_serialize"
version = "1.0.2"
edition = "2021"
authors = ["James Hoerr"]
description = "Low Level Support Package for dg_xch_utils"

[dependencies]
bytes = "1.4.0"
log = "0.4.17"
sha2 = "0.10.6"