[package]
name = "dg_xch_keys"
description = "Key Management Utils the Chia Blockchain"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
bech32 = "0.11.1"
bip39 = {version= "2.2.2", features=["rand", "zeroize"] }
blst = { version = "0.3.16", features = ["portable"] }
dg_xch_core = {path = "../core", version = "3.0.0", default-features = false, features = ["bls"] }
dg_xch_puzzles = {path = "../puzzles", version="3.0.0"}
hex = "0.4.3"
hkdf = "0.12.4"
sha2 = "0.10.9"
zeroize = "1.9.0"
