[package]
name = "dg_xch_keys"
version = "1.0.2"
edition = "2021"
authors = ["James Hoerr"]
description = "Key Management Utils the Chia Blockchain"

[dependencies]
bech32 = "0.9.1"
blst = "0.3.7"
bip39 = {version= "2.0.0", features=["rand"] }
dg_xch_core = {version = "1.0.3", features = ["paperclip"] }
dg_xch_puzzles = "1.0.3"
hkdf = "0.12.3"
sha2 = "0.10.6"