on:
  push:
    branches:
      - main
  pull_request:

name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  lint-and-build:
    name: Lint and Build
    uses: ./.github/workflows/lint-and-build.yml
